name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Compile Resource File
      run: |
        windres resource.rc -O coff -o resource.res

    - name: Compile Executable
      run: |
        g++ -Os -s -static monitor_hz.cpp resource.res -o monitor_hz.exe -luser32

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        files: monitor_hz.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}